server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
#  servlet:
#    session:
#      timeout: 1m
spring:
  datasource:
    password: higuys
    maxIdle: 50
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 600000
    maxWait: 120000
    url: jdbc:mysql://127.0.0.1:3306/security_login?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&zeroDateTimeBehavior=round&serverTimezone=UTC
    maxActive: 255
    username: root
  jpa:
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
